version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets

  cov:
    desc: Generates the code coverage report in text format printed to stdout
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage

  cov-html:
    desc: Generates the code coverage report in HTML format and opens it in a browser
    cmds:
      - cmd: cargo +stable llvm-cov clean
      - cmd: cargo +stable llvm-cov --no-cfg-coverage --html --open

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc --no-deps

  doc-open:
    desc: Generates documentation and opens it in browser
    cmds:
      - cmd: cargo +stable doc --no-deps --open

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt

  help:
    desc: Runs short help option
    cmds:
      - cmd: cargo +stable run -- -h

  help-long:
    desc: Runs long help option
    cmds:
      - cmd: cargo +stable run -- --help

  install:
    desc: Builds and installs release version
    cmds:
      - cmd: cargo +stable install biff --path=. --force

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +stable test

  testn:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +stable nextest run
